name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Add fruit and print test
      id: add-fruit-and-print-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: Add fruit and print test
        setup-command: ''
        command: python3 add_fruit/main.py
        input: mango
        expected-output: "^apple\\nbanana\\nmango\\n?$"
        comparison-method: regex
        timeout: 10
        max-score: 5
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        ADD-FRUIT-AND-PRINT-TEST_RESULTS: "${{steps.add-fruit-and-print-test.outputs.result}}"
      with:
        runners: add-fruit-and-print-test
